services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: studentdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    image: suryakiran1993/docker-backend:latest
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb

  frontend:
    image: suryakiran1993/docker-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
